version: '3'
services:
  drone-server:
    image: drone/drone:latest
    ports:
      - "8012:80"
    volumes:
      - ./drone:/var/lib/drone/
    environment:
      - DRONE_OPEN=true
      - DRONE_SERVER_HOST=47.113.91.65:8012
      - DRONE_DEBUG=true
      - DRONE_GIT_ALWAYS_AUTH=false
      - DRONE_GITLAB_SERVER=http://47.113.91.65
      - DRONE_GITLAB_CLIENT_ID=85bc051f90a6e24ef9866475b9126b1e37a54bc1dd7f9ed326c2f4a406909a81
      - DRONE_GITLAB_CLIENT_SECRET=cf0af91d144c18d0fc3572b7328177bfb9838c63a59e867cb2b187661e2d4198
      - DRONE_PROVIDER=gitlab
      - DRONE_SERVER_PROTO=http
      - DRONE_GITLAB_SKIP_VERIFY=true
      - DRONE_RPC_SECRET=d92949cc1278c6a2e5635f6ba0760ce2
  mysql:
    image: mysql:5.7.16
    volumes:
      - ./gogs/mysql:/var/lib/mysql
    ports:
      - 3308:3306
    command: --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
    environment:
      MYSQL_ROOT_PASSWORD: dalongrong
      MYSQL_DATABASE: gogs
      MYSQL_USER: gogs
      MYSQL_PASSWORD: dalongrong
      TZ: Asia/Shanghai
  drone-agent:
    image: drone/agent:latest
    depends_on:
      - drone-server
    environment:
      - DRONE_RPC_SERVER=drone-server
      - DRONE_RPC_SECRET=d92949cc1278c6a2e5635f6ba0760ce2
      - DRONE_DEBUG=true
      - DOCKER_HOST=tcp://docker-bind:2375
  docker-bind:
     image: docker:dind
     privileged: true
     command: --storage-driver=overlay
