version: "3"
services:
  flask_adminapp:
    image: easytaskadmin:latest
    container_name: easytaskadmin
    restart: always
    network_mode: bridge
    ports:
      - "8009:8000"
    command: sh run_docker.sh
    volumes:
      - ./logs:/back_server/logs
      - .:/back_server